[package]
name = "patal-pattern"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
patal-geometry = { path = "../geometry" }
patal-materials = { path = "../materials" }
serde = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
